//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace StackTraceDatabase
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class StackTraceDBEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new StackTraceDBEntities object using the connection string found in the 'StackTraceDBEntities' section of the application configuration file.
        /// </summary>
        public StackTraceDBEntities() : base("name=StackTraceDBEntities", "StackTraceDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new StackTraceDBEntities object.
        /// </summary>
        public StackTraceDBEntities(string connectionString) : base(connectionString, "StackTraceDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new StackTraceDBEntities object.
        /// </summary>
        public StackTraceDBEntities(EntityConnection connection) : base(connection, "StackTraceDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<StackTrace> StackTraces
        {
            get
            {
                if ((_StackTraces == null))
                {
                    _StackTraces = base.CreateObjectSet<StackTrace>("StackTraces");
                }
                return _StackTraces;
            }
        }
        private ObjectSet<StackTrace> _StackTraces;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the StackTraces EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToStackTraces(StackTrace stackTrace)
        {
            base.AddObject("StackTraces", stackTrace);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="StackTraceDBModel", Name="StackTrace")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class StackTrace : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new StackTrace object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static StackTrace CreateStackTrace(global::System.Int32 id)
        {
            StackTrace stackTrace = new StackTrace();
            stackTrace.ID = id;
            return stackTrace;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String StackTrace1
        {
            get
            {
                return _StackTrace1;
            }
            set
            {
                OnStackTrace1Changing(value);
                ReportPropertyChanging("StackTrace1");
                _StackTrace1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("StackTrace1");
                OnStackTrace1Changed();
            }
        }
        private global::System.String _StackTrace1;
        partial void OnStackTrace1Changing(global::System.String value);
        partial void OnStackTrace1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DumpFile
        {
            get
            {
                return _DumpFile;
            }
            set
            {
                OnDumpFileChanging(value);
                ReportPropertyChanging("DumpFile");
                _DumpFile = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DumpFile");
                OnDumpFileChanged();
            }
        }
        private global::System.String _DumpFile;
        partial void OnDumpFileChanging(global::System.String value);
        partial void OnDumpFileChanged();

        #endregion

    
    }

    #endregion

    
}
