//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsExports
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commands
    {
        public string Name { get; set; }
        public int OwnerID { get; set; }
        public int ID { get; set; }
        public byte[] Binary { get; set; }
    
        public virtual Owner Owner { get; set; }
    }
}
