//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SplunkLite.Net.Rest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public int ID { get; set; }
        public System.DateTime Timestamp { get; set; }
        public string Raw { get; set; }
        public string Host { get; set; }
        public string Source { get; set; }
        public string SourceType { get; set; }
    }
}
